#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$extractor = new \Dfv\DoctrineProtoExtractor\Command\ExtractCommand();

$application->add($extractor);
$application->setDefaultCommand($extractor->getName());

$application->run();
