doctrine-proto:
    protoVersion: proto3
    denormalizationGroupTemplate: '{className}_update'
    service: gRPCServiceName
    from: file:///my/doctrine/project/src/Entity
    to: file:///my/project/grpc/path/
    package: company.service
    goPackage: gitlab.com/group/project;pb
    filename: /output/entities.proto